

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/musacreativa_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1212marzo}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


server.port=${PORT:8080}
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

jwt.secret=${JWT_SECRET:clave-super-secreta-musacreativa-2024}
jwt.expiration=86400000
